### ISSUE TITLE
Resources Consumption

### ISSUE THREAD

**Issue by veez77** [philips-software/logviewer#6]
While reading logs, Since Analogy is consuming the System memeory,
It will be great if the Analogy will be able to close gracefully (or even take a snapshot of last closer state) in case of no usage of the System

**Comment by LiorBanai** [comment]
When Analogy is subscribed to receive new messages even if the user is away and new message are being transmitted  those messages will keep accomulated in the viewer. After log time the amount of messages could pass the millions marks and the memory usage will be at the GB level.

In order to handle this situation a possible solution is as follow: when the application detects idle time no more messages will be collected. Upon new user interaction a message will be displayed to notify the user X number of message were missed due to inactivity

the idle/inactivity period will be configurable under the user settings window (eg.: Inactivity time: X 
 minutes)
